apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: compose-api-local

images:
  - name: ghcr.io/biosimulations/compose-api
    newTag: 0.0.1

resources:
  - alembic-job.yaml
  - secret-shared.yaml
  - secret-ghcr.yaml
  - ../../config/compose-api-local
