openapi: 3.1.0
info:
  title: compose-api
  version: 0.2.5
paths:
  /core/simulator/versions:
    get:
      tags:
      - Simulators
      summary: get the list of available simulator versions
      operationId: get-simulator-versions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredSimulators'
  /core/simulation/run:
    post:
      tags:
      - Simulations
      summary: Run a simulation
      operationId: run-simulation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulationRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulationExperiment'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/versions:
    get:
      tags:
      - Simulations
      summary: Get list of simulations
      operationId: get-simulation-versions
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Simulation'
                type: array
                title: Response Get-Simulation-Versions
  /core/simulation/run/status:
    get:
      tags:
      - Simulations
      summary: Get the simulation status record by its ID
      operationId: get-simulation-status
      parameters:
      - name: simulation_id
        in: query
        required: true
        schema:
          type: integer
          title: Simulation Id
      - name: num_events
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Num Events
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HpcRun'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/events:
    get:
      tags:
      - Simulations
      summary: Get the worker events for a simulation by its ID
      operationId: get-simulation-worker-events
      parameters:
      - name: simulation_id
        in: query
        required: true
        schema:
          type: integer
          title: Simulation Id
      - name: num_events
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Num Events
      - name: prev_sequence_number
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Prev Sequence Number
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkerEvent'
                title: Response Get-Simulation-Worker-Events
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/results/chunks:
    get:
      tags:
      - Simulations
      summary: Get simulation results in chunks
      operationId: get-simulation-results
      parameters:
      - name: experiment_id
        in: query
        required: false
        schema:
          type: string
          default: experiment_96bb7a2_id_1_20250620-181422
          title: Experiment Id
      - name: database_id
        in: query
        required: true
        schema:
          type: integer
          description: Database Id returned from /submit-simulation
          title: Database Id
        description: Database Id returned from /submit-simulation
      - name: git_commit_hash
        in: query
        required: false
        schema:
          type: string
          default: not-specified
          title: Git Commit Hash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_get-simulation-results'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /core/simulation/run/results/file:
    get:
      tags:
      - Simulations
      summary: Get simulation results as a zip file
      operationId: get-simulation-results-file
      parameters:
      - name: experiment_id
        in: query
        required: false
        schema:
          type: string
          default: experiment_96bb7a2_id_1_20250620-181422
          title: Experiment Id
      - name: database_id
        in: query
        required: false
        schema:
          type: integer
          description: Database Id of simulation
          title: Database Id
        description: Database Id of simulation
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              - $ref: '#/components/schemas/Settings'
              - type: 'null'
              title: Settings
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /health:
    get:
      tags:
      - BIOSIM API
      summary: Check Health
      operationId: check_health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
                title: Response Check Health Health Get
  /version:
    get:
      tags:
      - BIOSIM API
      summary: Get Version
      operationId: get_version_version_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Version Version Get
components:
  schemas:
    Body_get-simulation-results:
      properties:
        observable_names:
          $ref: '#/components/schemas/RequestedObservables'
        settings:
          anyOf:
          - $ref: '#/components/schemas/Settings'
          - type: 'null'
      type: object
      required:
      - observable_names
      title: Body_get-simulation-results
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HpcRun:
      properties:
        database_id:
          type: integer
          title: Database Id
        slurmjobid:
          type: integer
          title: Slurmjobid
        correlation_id:
          type: string
          title: Correlation Id
        job_type:
          $ref: '#/components/schemas/JobType'
        ref_id:
          type: integer
          title: Ref Id
        status:
          anyOf:
          - $ref: '#/components/schemas/JobStatus'
          - type: 'null'
        start_time:
          anyOf:
          - type: string
          - type: 'null'
          title: Start Time
        end_time:
          anyOf:
          - type: string
          - type: 'null'
          title: End Time
        error_message:
          anyOf:
          - type: string
          - type: 'null'
          title: Error Message
      type: object
      required:
      - database_id
      - slurmjobid
      - correlation_id
      - job_type
      - ref_id
      title: HpcRun
    JobStatus:
      type: string
      enum:
      - waiting
      - queued
      - running
      - completed
      - failed
      title: JobStatus
    JobType:
      type: string
      enum:
      - simulation
      title: JobType
    RegisteredSimulators:
      properties:
        versions:
          items:
            $ref: '#/components/schemas/SimulatorVersion'
          type: array
          title: Versions
        timestamp:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Timestamp
      type: object
      required:
      - versions
      title: RegisteredSimulators
    RequestedObservables:
      properties:
        items:
          items:
            type: string
          type: array
          title: Items
      type: object
      title: RequestedObservables
    Settings:
      properties:
        storage_bucket:
          type: string
          title: Storage Bucket
          default: files.biosimulations.dev
        storage_endpoint_url:
          type: string
          title: Storage Endpoint Url
          default: https://storage.googleapis.com
        storage_region:
          type: string
          title: Storage Region
          default: us-east4
        storage_tensorstore_driver:
          type: string
          enum:
          - zarr
          - n5
          - zarr3
          title: Storage Tensorstore Driver
          default: zarr3
        storage_tensorstore_kvstore_driver:
          type: string
          enum:
          - file
          - s3
          - gcs
          title: Storage Tensorstore Kvstore Driver
          default: gcs
        temporal_service_url:
          type: string
          title: Temporal Service Url
          default: localhost:7233
        storage_local_cache_dir:
          type: string
          title: Storage Local Cache Dir
          default: ./local_cache
        storage_gcs_credentials_file:
          type: string
          title: Storage Gcs Credentials File
          default: ''
        mongodb_uri:
          type: string
          title: Mongodb Uri
          default: mongodb://localhost:27017
        mongodb_database:
          type: string
          title: Mongodb Database
          default: biosimulations
        mongodb_collection_omex:
          type: string
          title: Mongodb Collection Omex
          default: BiosimOmex
        mongodb_collection_sims:
          type: string
          title: Mongodb Collection Sims
          default: BiosimSims
        mongodb_collection_compare:
          type: string
          title: Mongodb Collection Compare
          default: BiosimCompare
        postgres_user:
          type: string
          title: Postgres User
          default: <USER>
        postgres_password:
          type: string
          title: Postgres Password
          default: <PASSWORD>
        postgres_database:
          type: string
          title: Postgres Database
          default: compose_api
        postgres_host:
          type: string
          title: Postgres Host
          default: localhost
        postgres_port:
          type: integer
          title: Postgres Port
          default: 5432
        postgres_pool_size:
          type: integer
          title: Postgres Pool Size
          default: 10
        postgres_max_overflow:
          type: integer
          title: Postgres Max Overflow
          default: 5
        postgres_pool_timeout:
          type: integer
          title: Postgres Pool Timeout
          default: 30
        postgres_pool_recycle:
          type: integer
          title: Postgres Pool Recycle
          default: 1800
        slurm_submit_host:
          type: string
          title: Slurm Submit Host
          default: ''
        slurm_submit_user:
          type: string
          title: Slurm Submit User
          default: ''
        slurm_submit_key_path:
          type: string
          title: Slurm Submit Key Path
          default: ''
        slurm_submit_known_hosts:
          anyOf:
          - type: string
          - type: 'null'
          title: Slurm Submit Known Hosts
        slurm_partition:
          type: string
          title: Slurm Partition
          default: ''
        slurm_node_list:
          type: string
          title: Slurm Node List
          default: ''
        slurm_qos:
          type: string
          title: Slurm Qos
          default: ''
        slurm_log_base_path:
          type: string
          title: Slurm Log Base Path
          default: ''
        slurm_base_path:
          type: string
          title: Slurm Base Path
          default: ''
        hpc_image_base_path:
          type: string
          title: Hpc Image Base Path
          default: ''
        hpc_repo_base_path:
          type: string
          title: Hpc Repo Base Path
          default: ''
        hpc_sim_base_path:
          type: string
          title: Hpc Sim Base Path
          default: ''
        hpc_sim_config_file:
          type: string
          title: Hpc Sim Config File
          default: publish.json
        nats_url:
          type: string
          title: Nats Url
          default: ''
        nats_worker_event_subject:
          type: string
          title: Nats Worker Event Subject
          default: worker.events
        nats_emitter_url:
          type: string
          title: Nats Emitter Url
          default: ''
        nats_emitter_magic_word:
          type: string
          title: Nats Emitter Magic Word
          default: emitter-magic-word
        dev_mode:
          type: string
          title: Dev Mode
          default: '0'
        app_dir:
          type: string
          title: App Dir
          default: /Users/jimschaff/Documents/workspace/compose-api/app
        assets_dir:
          type: string
          title: Assets Dir
          default: /Users/jimschaff/Documents/workspace/compose-api/assets
        marimo_api_server:
          type: string
          title: Marimo Api Server
          default: ''
      additionalProperties: false
      type: object
      title: Settings
    Simulation:
      properties:
        database_id:
          type: integer
          title: Database Id
        sim_request:
          $ref: '#/components/schemas/SimulationRequest'
        slurmjob_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Slurmjob Id
      type: object
      required:
      - database_id
      - sim_request
      title: Simulation
    SimulationExperiment:
      properties:
        experiment_id:
          type: string
          title: Experiment Id
        simulation:
          $ref: '#/components/schemas/Simulation'
        last_updated:
          type: string
          title: Last Updated
        metadata:
          additionalProperties:
            type: string
          type: object
          title: Metadata
      type: object
      required:
      - experiment_id
      - simulation
      title: SimulationExperiment
    SimulationRequest:
      properties:
        simulator:
          $ref: '#/components/schemas/SimulatorVersion'
        variant_config:
          additionalProperties:
            additionalProperties:
              anyOf:
              - type: integer
              - type: number
              - type: string
            type: object
          type: object
          title: Variant Config
      type: object
      required:
      - simulator
      - variant_config
      title: SimulationRequest
    SimulatorVersion:
      properties:
        git_commit_hash:
          type: string
          title: Git Commit Hash
        git_repo_url:
          type: string
          title: Git Repo Url
        git_branch:
          type: string
          title: Git Branch
        database_id:
          type: integer
          title: Database Id
        created_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Created At
      type: object
      required:
      - git_commit_hash
      - git_repo_url
      - git_branch
      - database_id
      title: SimulatorVersion
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    WorkerEvent:
      properties:
        database_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Database Id
        created_at:
          anyOf:
          - type: string
          - type: 'null'
          title: Created At
        hpcrun_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Hpcrun Id
        correlation_id:
          type: string
          title: Correlation Id
        sequence_number:
          type: integer
          title: Sequence Number
        mass:
          additionalProperties:
            type: number
          type: object
          title: Mass
        time:
          type: number
          title: Time
      type: object
      required:
      - correlation_id
      - sequence_number
      - mass
      - time
      title: WorkerEvent
