apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: compose-postgres-cluster
  namespace: postgres-cluster
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  bootstrap:
    initdb:
      database: compose_api
      owner: compose_api

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true
