apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # corresponds to the NFS mount of cfs07:/ifs/vcell to /share/apps/vcell7 on swarm nodes
  name: crbmapi-home-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1000Gi
  volumeName: crbmapi-home-pv
